apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vm-templates
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/David-VTUK/kubevirt-argocd-demo-app-of-apps.git
    targetRevision: HEAD
    path: vm-templates
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true